# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 884d8935eb3a6a1d90d8a41a18d23a961b2743498b91138718601a220dbcf184e802d3a005c98b4223f687b7f18bc3c5ef128b60a49ea89083937f33449d6038

test:
  secret_key_base: 41283291ea2c21352201e066e8cdbe097b84aa4fdb41f16cce16a649928efa1ff2c8a008fdd047d7be6775b46bbde36db553d99d1fe162b1d4a9026e019d2e7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
